parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $cookieConsentTheme: '%ch_cookie_consent.theme%'
            $cookieCategories: '%ch_cookie_consent.categories%'
            $useLogger: '%ch_cookie_consent.use_logger%'
            $cookiePrefix: '%ch_cookie_consent.cookie_prefix%'
            $cookieKeyName: '%ch_cookie_consent.cookie_key_name%'
            $cookieConsentName: '%ch_cookie_consent.cookie_consent_name%'
            $cookieConsentCategory: '%ch_cookie_consent.cookie_category_name_prefix%'

    ConnectHolland\CookieConsentBundle\:
        resource: '../../'
        exclude: '../../{vendor}'

    ConnectHolland\CookieConsentBundle\Controller\:
        resource: '../../Controller/*'
        public: true

    ConnectHolland\CookieConsentBundle\Enum\:
        resource: '../../Enum/CookieNameEnum.php'
        public: true

    ConnectHolland\CookieConsentBundle\Cookie\CookieChecker:
        arguments:
            - "@=service('request_stack').getCurrentRequest()"

    ConnectHolland\CookieConsentBundle\Cookie\CookieLogger:
        arguments:
            $request: "@=service('request_stack').getCurrentRequest()"
